services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rozz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - /home/rozz/modern-api/postgresdb/database:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
