services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rozz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - C:\Users\abdul-majid.nuhu\Desktop\collections\java-spring
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
